### ISSUE TITLE
Current config error

### ISSUE THREAD

**Issue by pongoman** [aofdev/vue-pwa-speech#1]
Hi, cool app!

When I tried cloning this project with the `git clone git@github.com:aofdev/vue-pwa-speech.git` it failed with the following error.
![screenshot_8](https://user-images.githubusercontent.com/14333747/31461076-082b5a04-aed1-11e7-8841-5072d696ac88.png)
I used another to download it.

After installation, I got an error: sample_rate_hertz (44100) in RecognitionConfig must either be omitted or match the value in the WAV header ( 48000).
So I changed `"sampleRateHertz": '48000'` and it worked. 

Not sure if I missed anything at the installation. 
Cheers

**Comment by aofdev** [comment]
thanks open issus but try I installed done ,i haven't installed any problems.  i Let's see if something goes wrong.

**Comment by pongoman** [comment]
I don't know what might have caused this, I opened the issue to give you a heads up.

Feel free to close it.
